# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CaddyConnect For Caddies’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CaddyConnect For Caddies
	
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'


  target 'CaddyConnect For CaddiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CaddyConnect For CaddiesUITests’ do
    inherit! :search_paths
    # Pods for testing
  end

end
